import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { getSession } from 'next-auth/client';
import Head from 'next/head';
import Layout from '../components/Layout';
import LoginForm from '../components/LoginForm';
import SignUpForm from '../components/SignUpForm';
import { NotificationsProvider } from '../contexts/NotificationContext';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true); // create own loading state so that the page content doesnt display whilst loading
  const router = useRouter();

  useEffect(() => {
    getSession().then((session) => {
      if (session) {
        router.replace('/profile');
      } else {
        setIsLoading(false);
      }
    });
  }, [router]);

  if (isLoading) {
    return <p>loading...</p>;
  }

  const forms = (
    <>
      <SignUpForm />
      <LoginForm />
    </>
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <section className='signupLoginForm flex'>{forms}</section>
      </main>
    </div>
  );
}
